### ISSUE TITLE
Cannot start up app

### ISSUE THREAD

**Issue by Borewit** [teken/audiobookplayer#4]
Hi @teken, I tried to start up you app.

I got a webpack compile an error:

`TypeError: window.require is not a function`

caused by:

https://github.com/teken/audiobookplayer/blob/0853f90ec077c18571d359246fefcc248a5c44c3/src/components/library/Library.js#L17-L18

Looks like, the main and rendered process got a bit mixed up there.

I think [this is the way](https://www.electronjs.org/docs/api/ipc-main) to address that.

Probably not the latest version.

**Comment by teken** [comment]
Closed due to starting app through a browser and not through electron
